apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube 
  serviceName: sonarqube
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: asia.gcr.io/portal-261602/sonarqube
        ports:
        - containerPort: 9000
          name: sonarqube
        volumeMounts:
        - name: sonarqube
          mountPath: /opt
  volumeClaimTemplates:
  - metadata:
      name: sonarqube
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi