apiVersion: v1
kind: Service
metadata:
  labels:
    app: metabase
  name: metabase
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: metabase