version: '2'
volumes:
  onto:
    driver: local
  pgdata:
    driver: local
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  ontoserver:
    image: aehrc/ontoserver:ctsa-5.6
    container_name: ontoserver
    depends_on:
      - db
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      - authentication.oauth.endpoint.client_id.0=ca12cb4e-75b8-4293-b473-46344d44b4a0
      - authentication.oauth.endpoint.client_secret.0=91505686-436e-4a5d-894e-c658d5a7ea19
      - ONTOSERVER_INSECURE=true
      - JAVA_OPTS=-Xmx2G        # Minimum
#      - JAVA_OPTS=-Xmx8G      # Preferred
    volumes:
      - onto:/var/onto