apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsq
  labels:
    app: nsq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsq
  template:
    metadata:
      labels:
        app: nsq
    spec:
      containers:
        - image: asia.gcr.io/portal-261602/nsq
          name: nsq
          ports:
            - containerPort: 8200
              name: nsq