apiVersion: v1
kind: Service
metadata:
  labels:
    app: prisma
  name: prisma
spec:
  type: LoadBalancer
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    app: prisma