apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault 
  serviceName: vault
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: asia.gcr.io/portal-261602/vault
        command: ["server"]
        ports:
        - containerPort: 8200
          name: vault
        volumeMounts:
        - name: vault
          mountPath: /vault
  volumeClaimTemplates:
  - metadata:
      name: vault
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi