apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
spec:
  type: LoadBalancer
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app: vault